"""
Lattice Reduction Cost Model Fitting — Baseline
=================================================
Empirical benchmarking for post-quantum cryptography security estimation.

The security of NIST's post-quantum standards (Kyber/ML-KEM, Dilithium/ML-DSA)
rests on the hardness of LWE, which reduces to lattice problems. NIST claims
these schemes provide 128/192/256-bit security, but these claims depend on
theoretical cost models (Core-SVP) that may not match reality.

This script fits empirical cost models from actual BKZ lattice reduction
benchmarks and extrapolates to answer: **Are NIST's claimed security levels
accurate under both classical and quantum attack models?**

The key PQC distinction:
  - Classical attacker: SVP oracle costs 2^{0.292·β} (sieving)
  - Quantum attacker:   SVP oracle costs 2^{0.265·β} (Grover-accelerated sieving)
  Same lattice, same β, but ~10% fewer security bits against a quantum adversary.

The agent modifies THIS FILE to improve PRED_SCORE.

PRED_SCORE = weighted combination of:
  - Interpolation R² on held-out instance GROUPS within training dims (30%)
  - Extrapolation R² on higher-dimension instances (50%)
  - Theory alignment: Spearman rank correlation with Core-SVP (primal only) (20%)

Usage:  timeout 300 python train.py
"""

import os, time, json, math, warnings
import numpy as np
import torch
import torch.nn as nn

SEED = 42
MAX_RUN_TIME = 295
np.random.seed(SEED)
torch.manual_seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ─────────────────────────────────────────────
# Load Data
# ─────────────────────────────────────────────
data = torch.load("lattice_benchmark.pt", weights_only=False)
rows = data["flat_rows"]
nist_params = data["nist_params"]
config = data["config"]

print(f"Loaded {len(rows)} data points from lattice_benchmark.pt")
print(f"  Dims: {config['dimensions']} (main) + {config['extrap_dimensions']} (extrap)")
print(f"  Attacks: {config['attack_types']}")
print(f"  Backend: {config['backend']}")

# Validate that the .pt file matches current prepare.py expectations.
# If you see warnings here, regenerate with: python prepare.py
_expected_betas = [10, 15, 20, 25, 30, 35]
_expected_dims = [40, 50, 60]
if config.get("bkz_betas") != _expected_betas:
    print(f"  WARNING: bkz_betas in data {config.get('bkz_betas')} != expected {_expected_betas}")
    print(f"           Data was generated by a different prepare.py version.")
if config.get("dimensions") != _expected_dims:
    print(f"  WARNING: dimensions in data {config.get('dimensions')} != expected {_expected_dims}")
    print(f"           Data was generated by a different prepare.py version.")
print(f"  Config source of truth: lattice_benchmark.pt (not prepare.py defaults)")


# ─────────────────────────────────────────────
# Feature Engineering
# ─────────────────────────────────────────────
def hermite_factor(beta):
    """
    BKZ root-Hermite factor — leading term (prepare.py convention).
    δ = (β/(2πe))^{1/(2(β-1))} — omitting the (πβ)^{1/β} refinement
    so that compute_theory_log2 produces the same beta_est as prepare.py.
    """
    if beta <= 1:
        return 1.5
    log_delta = math.log(beta / (2 * math.pi * math.e)) / (2 * (beta - 1))
    return math.exp(log_delta)


def compute_theory_log2(n, q, sigma_eff, d):
    """
    Estimate theory_classical_log2 using Core-SVP + GSA uSVP condition.
    Returns 0.292 * beta_star where beta_star is the minimum block size
    satisfying the Gaussian heuristic for primal uSVP attack.

    Uses the same hermite_factor formula and optimal_m as prepare.py:
      m = max(n, min(2n, ceil(n*log(q)/log(max(q/2,2)))))
      d = m + n + 1 (primal lattice dimension)
      δ = (β/(2πe))^{1/(2(β-1))}
      condition: d*log(δ) + log_vol/d ≤ log(σ√(m+n))
    """
    # match prepare.py's optimal_m
    m = max(n, min(2 * n, int(math.ceil(n * math.log(q) / math.log(max(q / 2, 2))))))
    target_norm = max(sigma_eff, 0.1) * math.sqrt(n + m)
    log_vol = m * math.log(q)
    log_target = math.log(max(target_norm, 1e-10))

    best_beta = d  # fallback: full dimension
    for b in range(5, d + 1):
        if b <= 1:
            continue
        log_delta = math.log(b / (2 * math.pi * math.e)) / (2 * (b - 1))
        log_predicted = d * log_delta + log_vol / d
        if log_predicted <= log_target:
            best_beta = b
            break

    return 0.292 * best_beta


def extract_features(row):
    """
    Extract features from a single data row.
    Returns: feature vector, log2(wall_time) target.

    All features must be computable at NIST-extrapolation time
    (i.e., no realized error_norm or other instance-specific quantities
    that would not be known for a hypothetical target instance).

    Features:
      0: log2(n)               — LWE dimension
      1: log2(q)               — modulus
      2: log2(sigma_eff)       — effective noise parameter
      3: beta                  — BKZ block size
      4: d                     — lattice dimension
      5: log2(d)               — log lattice dimension
      6: beta / d              — relative block size
      7: n * log2(q)           — volume proxy
      8: beta * log2(d)        — interaction: block size × lattice complexity
      9: is_dual               — 1.0 if dual attack, 0.0 if primal
     10: log2(beta)            — BKZ overhead term
     11: log2(d) - log2(beta)  — log(d/β): BKZ rounds
     12: beta * log2(beta)     — β·log(β): Stirling correction
     13: theory_classical_log2 — RADICAL: direct Core-SVP theory prediction
    """
    n = row["n"]
    q = row["q"]
    sigma = max(row["sigma_eff"], 0.1)
    beta = row["beta"]
    d = row["d"]
    is_dual = 1.0 if row["attack"] == "dual" else 0.0
    theory = row["theory_classical_log2"]

    features = [
        math.log2(n),
        math.log2(q),
        math.log2(sigma),
        beta,
        d,
        math.log2(d),
        beta / d,
        n * math.log2(q),
        beta * math.log2(d),
        is_dual,
        math.log2(beta),                       # 10: explicit log(β)
        math.log2(d) - math.log2(beta),         # 11: log(d/β) BKZ rounds
        beta * math.log2(beta),                 # 12: β·log(β) Stirling
        theory,                                 # 13: theory_classical_log2 DIRECT
    ]

    target = math.log2(max(row["wall_time"], 1e-6))
    return np.array(features, dtype=np.float64), target


def build_dataset(rows):
    """Build feature matrix X, target vector y, and metadata from flat rows."""
    X_list, y_list, meta_list = [], [], []

    for row in rows:
        if row["wall_time"] <= 0 or row["root_hermite_factor"] <= 0:
            continue
        feat, target = extract_features(row)
        X_list.append(feat)
        y_list.append(target)
        meta_list.append({
            "n": row["n"],
            "is_extrap": row["is_extrap"],
            "beta": row["beta"],
            "attack": row["attack"],
            "instance_group": row["instance_group"],
            "theory_classical_log2": row["theory_classical_log2"],
            "wall_time": row["wall_time"],
        })

    return np.array(X_list), np.array(y_list), meta_list


X_all, y_all, meta_all = build_dataset(rows)
print(f"Valid data points: {len(X_all)}")
print(f"  Feature dim: {X_all.shape[1]}")
print(f"  Target range: [{y_all.min():.2f}, {y_all.max():.2f}] (log2 seconds)")


# ─────────────────────────────────────────────
# Train/Test Split — BY INSTANCE GROUP, not by row
# ─────────────────────────────────────────────
# This prevents data leakage: all beta values for the same LWE instance
# go into the same split. Otherwise train and test share correlated samples.

train_dims = set(config["dimensions"])
extrap_dims = set(config["extrap_dimensions"])

# Separate extrapolation rows
extrap_mask = np.array([m["is_extrap"] for m in meta_all])
extrap_idx = np.where(extrap_mask)[0]

# Within training dims, split by instance_group (20% held out)
train_dim_mask = np.array([m["n"] in train_dims and not m["is_extrap"] for m in meta_all])
train_dim_idx = np.where(train_dim_mask)[0]

# Get unique instance groups in training data
train_groups = sorted(set(meta_all[i]["instance_group"] for i in train_dim_idx))
np.random.shuffle(train_groups)
n_holdout_groups = max(1, len(train_groups) // 5)
holdout_groups = set(train_groups[:n_holdout_groups])
fit_groups = set(train_groups[n_holdout_groups:])

train_idx = np.array([i for i in train_dim_idx if meta_all[i]["instance_group"] in fit_groups])
interp_test_idx = np.array([i for i in train_dim_idx if meta_all[i]["instance_group"] in holdout_groups])

X_train, y_train = X_all[train_idx], y_all[train_idx]
X_interp, y_interp = X_all[interp_test_idx], y_all[interp_test_idx]
X_extrap, y_extrap = X_all[extrap_idx], y_all[extrap_idx]

# Theory predictions for rank correlation — PRIMAL ONLY
# The theory model is a primal uSVP proxy; using it for dual rows
# would mix incompatible cost models and corrupt the correlation metric.
extrap_primal_mask = np.array([meta_all[i]["attack"] == "primal" for i in extrap_idx])
extrap_primal_local_idx = np.where(extrap_primal_mask)[0]  # indices into extrap arrays
theory_preds_extrap_primal = np.array([
    meta_all[extrap_idx[i]]["theory_classical_log2"] for i in extrap_primal_local_idx
])

n_primal_extrap = len(extrap_primal_local_idx)
n_dual_extrap = len(extrap_idx) - n_primal_extrap
print(f"  Train: {len(X_train)} ({len(fit_groups)} groups)")
print(f"  Interp test: {len(X_interp)} ({len(holdout_groups)} groups)")
print(f"  Extrap test: {len(X_extrap)} ({n_primal_extrap} primal, {n_dual_extrap} dual)")


# ─────────────────────────────────────────────
# Metrics
# ─────────────────────────────────────────────
def r_squared(y_true, y_pred):
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - y_true.mean()) ** 2)
    if ss_tot < 1e-12:
        return 0.0
    return 1.0 - ss_res / ss_tot


def spearman_rank_corr(x, y):
    from scipy.stats import spearmanr
    if len(x) < 3:
        return 0.0
    corr, _ = spearmanr(x, y)
    return corr if not math.isnan(corr) else 0.0


def compute_pred_score(y_interp_true, y_interp_pred,
                       y_extrap_true, y_extrap_pred,
                       theory_preds_primal, y_extrap_primal_preds):
    """
    Composite PRED_SCORE:
      0.3 * R²_interp + 0.5 * R²_extrap + 0.2 * theory_rank_correlation

    theory_rank_correlation uses PRIMAL extrapolation rows only,
    because the theory model is a primal uSVP proxy.
    Each component clipped to [0, 1].
    """
    r2_interp = max(0.0, r_squared(y_interp_true, y_interp_pred))
    r2_extrap = max(0.0, r_squared(y_extrap_true, y_extrap_pred)) if len(y_extrap_true) > 0 else 0.0

    if len(theory_preds_primal) > 2 and len(y_extrap_primal_preds) > 2:
        theory_corr = max(0.0, spearman_rank_corr(theory_preds_primal, y_extrap_primal_preds))
    else:
        theory_corr = 0.0

    score = 0.3 * r2_interp + 0.5 * r2_extrap + 0.2 * theory_corr
    return score, r2_interp, r2_extrap, theory_corr


# ─────────────────────────────────────────────
# Polynomial Feature Expansion
# ─────────────────────────────────────────────
def poly_features(X, degree=2):
    """
    Add polynomial and interaction features up to given degree.
    For degree=2: adds squares of each feature + pairwise products.
    Keeps is_dual binary (no squaring needed for indicator).
    """
    n, d = X.shape
    feats = [X]
    # Squares of continuous features (skip is_dual = col 9)
    sq = X[:, :9] ** 2
    feats.append(sq)
    # Pairwise products of most informative features
    # Exclude theory_classical_log2 [13] — only 5 distinct values → poly cross-terms overfit
    # Exclude log2(β) [10], log(d/β) [11], β·log(β) [12] — β cross-terms hurt theory_corr
    key_cols = [0, 1, 3, 5, 6, 7, 8]
    for i in range(len(key_cols)):
        for j in range(i+1, len(key_cols)):
            ci, cj = key_cols[i], key_cols[j]
            feats.append((X[:, ci] * X[:, cj]).reshape(-1, 1))
    return np.hstack(feats)


# ─────────────────────────────────────────────
# Baseline Model: Linear Regression
# ─────────────────────────────────────────────
def fit_linear_model(X_tr, y_tr, lam=1e-4):
    n, d = X_tr.shape
    X_aug = np.column_stack([X_tr, np.ones(n)])
    w = np.linalg.solve(X_aug.T @ X_aug + lam * np.eye(d + 1), X_aug.T @ y_tr)
    return w

def predict_linear(X, w):
    X_aug = np.column_stack([X, np.ones(X.shape[0])])
    return X_aug @ w


# ─────────────────────────────────────────────
# Baseline Model: Small Neural Network
# ─────────────────────────────────────────────
class CostMLP(nn.Module):
    def __init__(self, input_dim, hidden=(64, 32)):
        super().__init__()
        layers = []
        d_in = input_dim
        for h in hidden:
            layers += [nn.Linear(d_in, h), nn.ReLU(), nn.Dropout(0.1)]
            d_in = h
        layers.append(nn.Linear(d_in, 1))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x).squeeze(-1)


def pairwise_ranking_loss(preds, theory_vals, margin=0.1):
    """
    Pairwise ranking hinge loss for theory-consistent predictions.
    Penalizes pairs (i,j) where theory_i > theory_j but pred_i < pred_j + margin.
    Applied to primal training rows only; vectorized O(N²).
    """
    pred_diff = preds.unsqueeze(0) - preds.unsqueeze(1)           # [N, N]: pred_i - pred_j
    theory_diff = theory_vals.unsqueeze(0) - theory_vals.unsqueeze(1)  # [N, N]
    # Only penalize pairs with meaningfully different theory values (gap > 1.0 log2-bit)
    violation_mask = (theory_diff > 1.0).float()
    if violation_mask.sum() == 0:
        return torch.tensor(0.0, device=preds.device)
    violations = torch.relu(margin - pred_diff) * violation_mask
    return violations.sum() / violation_mask.sum()


def soft_spearman_loss(preds, theory_vals, temperature=1.0):
    """
    Differentiable negative Spearman rank correlation loss.
    Computes soft ranks via sigmoid pairwise comparisons, then Pearson
    correlation of soft ranks = differentiable Spearman approximation.
    Minimizing this maximizes theory rank alignment.
    Applied to primal training rows only.
    """
    n = preds.shape[0]
    if n < 3:
        return torch.tensor(0.0, device=preds.device)
    # Soft rank: sum of sigmoid(pred_i - pred_j) over j ≠ i → smooth rank proxy
    pred_diff = (preds.unsqueeze(0) - preds.unsqueeze(1)) / temperature  # [n, n]
    pred_soft_rank = torch.sigmoid(pred_diff).sum(1)  # [n]
    theory_diff = (theory_vals.unsqueeze(0) - theory_vals.unsqueeze(1)) / temperature
    theory_soft_rank = torch.sigmoid(theory_diff).sum(1)  # [n]
    # Pearson between soft ranks ≈ Spearman
    p = pred_soft_rank - pred_soft_rank.mean()
    t = theory_soft_rank - theory_soft_rank.mean()
    corr = (p * t).sum() / (torch.sqrt((p**2).sum() * (t**2).sum()) + 1e-8)
    return -corr  # negate: minimize = maximize correlation


def fit_neural_model(X_tr, y_tr, X_val, y_val, epochs=500, lr=1e-3, hidden=(64, 32),
                     rank_lambda=0.0, theory_tr=None, primal_mask_tr=None):
    mu = X_tr.mean(axis=0)
    std = X_tr.std(axis=0) + 1e-8
    X_tr_n = (X_tr - mu) / std
    X_val_n = (X_val - mu) / std

    X_t = torch.tensor(X_tr_n, dtype=torch.float32).to(device)
    y_t = torch.tensor(y_tr, dtype=torch.float32).to(device)
    X_v = torch.tensor(X_val_n, dtype=torch.float32).to(device)

    # Prepare ranking inputs (primal training rows only)
    primal_idx_t = None
    theory_t = None
    if rank_lambda > 0 and theory_tr is not None and primal_mask_tr is not None:
        pidx = np.where(primal_mask_tr)[0]
        if len(pidx) > 10:
            primal_idx_t = torch.tensor(pidx, dtype=torch.long).to(device)
            theory_t = torch.tensor(theory_tr[pidx], dtype=torch.float32).to(device)

    model = CostMLP(X_tr.shape[1], hidden=hidden).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    best_val_loss = float("inf")
    best_state = None

    for epoch in range(epochs):
        model.train()
        pred = model(X_t)
        mse_loss = nn.MSELoss()(pred, y_t)
        if rank_lambda > 0 and primal_idx_t is not None:
            rank_loss = soft_spearman_loss(pred[primal_idx_t], theory_t)
            loss = mse_loss + rank_lambda * rank_loss
        else:
            loss = mse_loss
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        scheduler.step()

        if epoch % 50 == 0 or epoch == epochs - 1:
            model.eval()
            with torch.no_grad():
                val_pred = model(X_v).cpu().numpy()
                val_loss = np.mean((y_val - val_pred) ** 2)
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            model.train()

    if best_state:
        model.load_state_dict(best_state)
    model.eval()

    def predict_fn(X_new):
        X_new_n = (X_new - mu) / std
        with torch.no_grad():
            return model(torch.tensor(X_new_n, dtype=torch.float32).to(device)).cpu().numpy()

    return predict_fn, model, mu, std



# ─────────────────────────────────────────────
# NIST Extrapolation
# ─────────────────────────────────────────────
def extrapolate_to_nist(predict_fn, nist_params, rows,
                        betas=[35, 60, 80, 100, 150, 200]):
    """
    NIST PQC parameter assessment — two separate analyses with distinct roles.

    Part A — RUNTIME EXTRAPOLATION (uses the fitted cost model)
      Predicts log₂(seconds) for BKZ-β at NIST-scale lattices.
      This is what the agent improves via PRED_SCORE. Machine-specific
      but gives an operational sense of feasibility.
      Units: log₂(seconds). NOT security bits.

    Part B — δ-BASED SECURITY ESTIMATE (uses raw benchmark δ(β), NOT the model)
      Fits δ(β) from empirical root-Hermite factors, extrapolates to find
      the β where δ is small enough to solve NIST instances.
      Then: classical bits = 0.292 × β*, quantum bits = 0.265 × β*.

      This IS in correct units (dimensionless security bits), but is a
      heuristic extrapolation with significant caveats:
        - δ measured at small β (≤40), extrapolated to β ~ 400–700
        - Polynomial BKZ overhead not captured in the δ model
        - Module-LWE structure not modeled (plain-LWE proxy)
        - Verdicts are exploratory, not validated security claims

    Future autoresearch direction: the agent could learn to predict δ(β)
    directly (not just runtime), which would tie Parts A and B together.
    """
    from collections import defaultdict

    print("\n" + "=" * 70)
    print("NIST PQC PARAMETER ASSESSMENT")
    print("(plain-LWE proxy — Module-LWE structure not modeled)")
    print("=" * 70)

    # ────────────────────────────────────────────────────────────
    # Part A: Runtime extrapolation using the fitted cost model
    # ────────────────────────────────────────────────────────────
    print("\n  PART A: Predicted BKZ runtimes at NIST scale")
    print("  (Uses the fitted cost model — improving PRED_SCORE improves these)")
    print("  (Units: log₂(seconds) — machine-specific, NOT security bits)")
    print("  " + "─" * 55)

    for name, params in nist_params.items():
        n = params["n"]
        q = params["q"]
        eta = params["eta1"]
        sigma = math.sqrt(eta / 2)
        claimed = params["claimed_bits"]
        m = n
        d = m + n + 1

        print(f"\n  {name}: n={n}, q={q}, claimed={claimed}-bit")

        for attack_label, d_val, is_dual in [("primal", d, 0.0), ("dual", m, 1.0)]:
            print(f"    [{attack_label:6s}]  ", end="")
            parts = []
            for beta in betas:
                if beta >= d_val:
                    continue
                theory_approx = compute_theory_log2(n, q, sigma, d_val)
                feat = np.array([
                    math.log2(n), math.log2(q), math.log2(max(sigma, 0.1)),
                    beta, d_val, math.log2(d_val), beta / d_val,
                    n * math.log2(q), beta * math.log2(d_val),
                    is_dual,
                    math.log2(beta),
                    math.log2(d_val) - math.log2(beta),
                    beta * math.log2(beta),
                    theory_approx,
                ]).reshape(1, -1)
                try:
                    log2_sec = float(predict_fn(feat)[0])
                    parts.append(f"β={beta}:{log2_sec:+.1f}")
                except Exception:
                    pass
            print("  ".join(parts) if parts else "no predictions")

    # ────────────────────────────────────────────────────────────
    # Part B: δ-based security estimates from raw benchmark data
    # ────────────────────────────────────────────────────────────
    print(f"\n\n  PART B: δ-based security estimates (HEURISTIC)")
    print("  (Uses raw δ(β) data, NOT the fitted cost model)")
    print("  " + "─" * 55)

    # Collect empirical δ(β) from primal benchmarks
    delta_by_beta = defaultdict(list)
    for row in rows:
        if row["attack"] != "primal":
            continue
        if row["root_hermite_factor"] > 0:
            delta_by_beta[row["beta"]].append(row["root_hermite_factor"])

    if not delta_by_beta:
        print("  No δ data available.")
        return []

    beta_vals = sorted(delta_by_beta.keys())
    delta_medians = [float(np.median(delta_by_beta[b])) for b in beta_vals]

    print(f"\n  Empirical δ(β) from primal benchmarks:")
    for b, d_med in zip(beta_vals, delta_medians):
        print(f"    β={b:3d}:  median δ = {d_med:.6f}")

    if len(beta_vals) < 3:
        print("  Too few β values to fit δ model.")
        return []

    # Fit δ(β) model: log(δ) ≈ a/β + b
    # As β → ∞, δ → exp(b) (asymptotic Hermite factor)
    inv_betas = np.array([1.0 / b for b in beta_vals])
    log_deltas = np.array([math.log(d) for d in delta_medians])
    coeffs = np.polyfit(inv_betas, log_deltas, 1)
    a_coeff, b_coeff = coeffs[0], coeffs[1]

    # Show fit quality
    delta_at_inf = math.exp(b_coeff)
    print(f"\n  Fitted model: log(δ) ≈ {a_coeff:.4f}/β + {b_coeff:.6f}")
    print(f"  Asymptotic δ (β→∞): {delta_at_inf:.6f}")
    print(f"  Fit residuals:")
    for b, d_med in zip(beta_vals, delta_medians):
        predicted = math.exp(a_coeff / b + b_coeff)
        print(f"    β={b:3d}:  actual={d_med:.6f}  predicted={predicted:.6f}  "
              f"err={d_med - predicted:+.6f}")

    # For each NIST scheme, find β* where δ^d · vol^{1/d} ≤ target_norm
    print(f"\n  Security estimates:")
    print(f"  {'─' * 65}")

    assessment_rows = []

    for name, params in nist_params.items():
        n = params["n"]
        q = params["q"]
        eta = params["eta1"]
        sigma = math.sqrt(eta / 2)
        claimed = params["claimed_bits"]
        m_p = n
        d_p = m_p + n + 1

        target_norm = sigma * math.sqrt(m_p + n)
        log_vol = m_p * math.log(q)
        log_target = math.log(max(target_norm, 1e-10))

        # Solve: d * log(δ(β)) + log_vol/d ≤ log(target_norm)
        # d * (a/β + b) ≤ log_target - log_vol/d
        rhs = log_target - log_vol / d_p
        # d*a/β ≤ rhs - d*b
        denom = rhs - d_p * b_coeff

        if denom > 0 and a_coeff * d_p > 0:
            beta_emp = int(math.ceil(a_coeff * d_p / denom))
        else:
            beta_emp = None

        if beta_emp is None or beta_emp < 2 or beta_emp > 100000:
            print(f"\n  {name}: β* estimation failed "
                  f"(δ model doesn't converge to target)")
            continue

        cl_bits = 0.292 * beta_emp
        qu_bits = 0.265 * beta_emp

        print(f"\n  {name} (n={n}, claimed={claimed}-bit):")
        print(f"    Empirical β* ≈ {beta_emp}  "
              f"(extrapolated from δ at β ≤ {max(beta_vals)})")
        print(f"    ┌─ Classical security (0.292 × β*): {cl_bits:.1f} bits  "
              f"[Δ = {cl_bits - claimed:+.1f}]")
        print(f"    └─ Quantum security   (0.265 × β*): {qu_bits:.1f} bits  "
              f"[Δ = {qu_bits - claimed:+.1f}]")

        for threat, bits in [("classical", cl_bits), ("quantum", qu_bits)]:
            delta_bits = bits - claimed
            if delta_bits > 10:
                verdict = "OVER-CONSERVATIVE"
            elif delta_bits > 2:
                verdict = "slightly over-conservative"
            elif delta_bits > -2:
                verdict = "CONSISTENT"
            elif delta_bits > -10:
                verdict = "slightly under-conservative"
            else:
                verdict = "UNDER-CONSERVATIVE"
            assessment_rows.append({
                "scheme": name, "threat_model": threat,
                "claimed_bits": claimed, "beta_empirical": beta_emp,
                "security_bits": bits, "delta_bits": delta_bits,
                "verdict": verdict,
            })

    # Summary
    if assessment_rows:
        print(f"\n  {'=' * 65}")
        print(f"  SUMMARY (HEURISTIC — extrapolated from β ≤ {max(beta_vals)})")
        print(f"  {'=' * 65}")
        print(f"  {'Scheme':<12s} {'Threat':<12s} {'β*':>5s} {'Claimed':>7s} "
              f"{'Est.':>6s} {'Δ':>6s}  Verdict")
        print(f"  {'─'*12} {'─'*12} {'─'*5} {'─'*7} {'─'*6} {'─'*6}  {'─'*25}")
        for r in assessment_rows:
            print(f"  {r['scheme']:<12s} {r['threat_model']:<12s} "
                  f"{r['beta_empirical']:>5d} {r['claimed_bits']:>7d} "
                  f"{r['security_bits']:>6.1f} {r['delta_bits']:>+6.1f}  "
                  f"{r['verdict']}")

        print(f"\n  CAVEATS:")
        print(f"  • β* extrapolated from δ measured at β ≤ {max(beta_vals)}")
        print(f"  • BKZ polynomial overhead not captured")
        print(f"  • Module-LWE → plain-LWE approximation")
        print(f"  • These are HEURISTIC exploratory estimates, not validated claims")

    return assessment_rows



# ─────────────────────────────────────────────
# Progress Tracking (delegated to plot_progress.py)
# ─────────────────────────────────────────────
from plot_progress import record_iteration, save_progress


# ─────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────
def main():
    t0 = time.time()

    if len(X_train) < 5:
        print("ERROR: Not enough training data. Run prepare.py first.")
        print("RESULT: PRED_SCORE=0.0000")
        return

    # ── Poly-ridge: λ selected via LODO-CV on training data (n=60 holdout) ──
    # NOTE: λ is chosen using only n=40,50 → n=60 CV, never touching extrap.
    # This section pre-computes the CV split needed for poly λ selection.
    X_train_poly = poly_features(X_train)
    X_interp_poly = poly_features(X_interp)
    X_extrap_poly = poly_features(X_extrap) if len(X_extrap) > 0 else X_extrap

    cv_dim_pre = max(config["dimensions"])
    cv_tr_mask_pre = np.array([meta_all[train_idx[i]]["n"] != cv_dim_pre
                                for i in range(len(X_train))])
    cv_val_mask_pre = ~cv_tr_mask_pre
    X_cv_tr_pre_poly = poly_features(X_train[cv_tr_mask_pre])
    X_cv_val_pre_poly = poly_features(X_train[cv_val_mask_pre])
    y_cv_tr_pre = y_train[cv_tr_mask_pre]
    y_cv_val_pre = y_train[cv_val_mask_pre]
    # Also get theory info on CV val for tc-aware selection
    cv_val_meta_pre = [meta_all[train_idx[i]] for i in range(len(X_train)) if cv_val_mask_pre[i]]
    cv_primal_mask_pre = np.array([m["attack"] == "primal" for m in cv_val_meta_pre])
    cv_theory_primal_pre = np.array([m["theory_classical_log2"] for m in cv_val_meta_pre
                                      if m["attack"] == "primal"])

    best_poly_cv_score = -1
    best_poly_lam = 1.0
    for lam in [1e-4, 1e-3, 1e-2, 0.1, 0.5, 1.0, 5.0, 10.0]:
        w = fit_linear_model(X_cv_tr_pre_poly, y_cv_tr_pre, lam=lam)
        y_cv_val_pred = predict_linear(X_cv_val_pre_poly, w)
        r2_cv = max(0.0, r_squared(y_cv_val_pre, y_cv_val_pred))
        tc_cv = max(0.0, spearman_rank_corr(cv_theory_primal_pre,
                    y_cv_val_pred[cv_primal_mask_pre])) \
                if cv_primal_mask_pre.any() and len(cv_theory_primal_pre) > 2 else 0.0
        cv_s = 0.6 * r2_cv + 0.4 * tc_cv
        if cv_s > best_poly_cv_score:
            best_poly_cv_score = cv_s
            best_poly_lam = lam

    # Retrain poly on ALL training data with CV-selected λ
    best_poly_w = fit_linear_model(X_train_poly, y_train, lam=best_poly_lam)
    y_ip_poly = predict_linear(X_interp_poly, best_poly_w)
    y_ep_poly = predict_linear(X_extrap_poly, best_poly_w) if len(X_extrap) > 0 else np.array([])
    y_ep_p_poly = y_ep_poly[extrap_primal_local_idx] if len(y_ep_poly) > 0 else np.array([])
    best_poly_score, r2i_poly, r2e_poly, tc_poly = compute_pred_score(
        y_interp, y_ip_poly, y_extrap, y_ep_poly,
        theory_preds_extrap_primal, y_ep_p_poly)
    print(f"  Poly-ridge (LODO-CV λ={best_poly_lam}): SCORE={best_poly_score:.4f} "
          f"(R²i={r2i_poly:.4f}, R²e={r2e_poly:.4f}, tc={tc_poly:.4f})")

    # ── Neural: tune rank_lambda via leave-one-dimension-out CV on training data ──
    # Use n=60 dimension as CV holdout; train on n=40,50; never touch extrap (n=70,80).
    # ── LODO-CV: joint (λ, β_poly) tuning — never touch extrap ──
    # Train on n=40,50; validate on n=60 (within training dims).
    # β_poly blends poly-ridge (high R²) with ranking-neural (high theory_corr).
    print("\n--- LODO-CV: joint (λ, β_poly) sweep (holdout dim=60) ---")
    cv_dim = max(config["dimensions"])
    cv_train_mask = np.array([meta_all[train_idx[i]]["n"] != cv_dim
                               for i in range(len(X_train))])
    cv_val_mask = ~cv_train_mask
    X_cv_tr, y_cv_tr = X_train[cv_train_mask], y_train[cv_train_mask]
    X_cv_val, y_cv_val = X_train[cv_val_mask], y_train[cv_val_mask]
    cv_val_meta = [meta_all[train_idx[i]] for i in range(len(X_train)) if cv_val_mask[i]]
    cv_primal_mask = np.array([m["attack"] == "primal" for m in cv_val_meta])
    cv_theory_primal = np.array([m["theory_classical_log2"] for m in cv_val_meta
                                  if m["attack"] == "primal"])
    theory_cv_tr = np.array([meta_all[train_idx[i]]["theory_classical_log2"]
                              for i in range(len(X_train)) if cv_train_mask[i]])
    primal_cv_tr = np.array([meta_all[train_idx[i]]["attack"] == "primal"
                              for i in range(len(X_train)) if cv_train_mask[i]])

    # Poly-ridge on n=40,50 CV fold
    X_cv_tr_poly = poly_features(X_cv_tr)
    X_cv_val_poly = poly_features(X_cv_val)
    best_cv_poly_w = None
    _best_cv_poly_s = -1
    for lam in [1e-4, 1e-3, 1e-2, 0.1, 1.0]:
        w = fit_linear_model(X_cv_tr_poly, y_cv_tr, lam=lam)
        s = r_squared(y_cv_val, predict_linear(X_cv_val_poly, w))
        if s > _best_cv_poly_s:
            _best_cv_poly_s = s
            best_cv_poly_w = w
    y_cv_poly = predict_linear(X_cv_val_poly, best_cv_poly_w)

    # ── OOF score function (used for family selection) ──
    def oof_score(y_pred_cv):
        """OOF CV score: 0.6*R²_cv + 0.4*theory_corr_cv (out-of-fold only)."""
        r2 = max(0.0, r_squared(y_cv_val, y_pred_cv))
        tc_v = max(0.0, spearman_rank_corr(cv_theory_primal, y_pred_cv[cv_primal_mask])) \
               if cv_primal_mask.any() and len(cv_theory_primal) > 2 else 0.0
        return 0.6 * r2 + 0.4 * tc_v

    # Poly-only OOF score (model trained on n=40,50, predictions on n=60 — true OOF)
    poly_oof = oof_score(y_cv_poly)

    # Best blend+neural OOF scores — tracked DURING the loop (models trained on n=40,50)
    best_cv_score = -1
    best_lambda_cv = 0.8
    best_beta_cv = 0.2
    best_nn_oof = -1      # best neural-only OOF (beta_poly=0.0)
    best_nn_oof_lam = 0.8

    for rank_lam in [0.5, 0.7, 0.8, 0.9, 1.0]:
        # Single CV model (simpler, consistent with earlier iters)
        torch.manual_seed(SEED)
        pred_cv, _, _, _ = fit_neural_model(
            X_cv_tr, y_cv_tr, X_cv_val, y_cv_val,
            epochs=600, lr=5e-4, hidden=(128, 64, 32),
            rank_lambda=rank_lam, theory_tr=theory_cv_tr, primal_mask_tr=primal_cv_tr
        )
        y_cv_nn = pred_cv(X_cv_val)
        for beta_poly in [0.0, 0.1, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5]:
            y_blend_cv = beta_poly * y_cv_poly + (1 - beta_poly) * y_cv_nn
            cv_score = oof_score(y_blend_cv)
            if cv_score > best_cv_score:
                best_cv_score = cv_score
                best_lambda_cv = rank_lam
                best_beta_cv = beta_poly
            # Track pure-neural OOF (beta_poly=0.0 → y_blend_cv = y_cv_nn)
            if beta_poly == 0.0 and cv_score > best_nn_oof:
                best_nn_oof = cv_score
                best_nn_oof_lam = rank_lam

    # ── OOF-based family selection ──
    # All three scores computed on n=60 holdout, models trained on n=40,50 — fully OOF.
    family_oof = {"poly": poly_oof, "neural": best_nn_oof, "blend": best_cv_score}
    winner_family = max(family_oof, key=family_oof.get)
    print(f"  OOF family scores: poly={poly_oof:.4f}  neural={best_nn_oof:.4f}  "
          f"blend={best_cv_score:.4f}")

    if winner_family == "neural":
        best_lambda_cv = best_nn_oof_lam
        best_beta_cv = 0.0
    elif winner_family == "poly":
        best_beta_cv = 1.0   # pure poly; best_lambda_cv unused for neural

    print(f"  → Winner by OOF: {winner_family} "
          f"(λ={best_lambda_cv if winner_family != 'poly' else 'N/A'}, "
          f"β_poly={best_beta_cv})")

    # ── Final fit on ALL training data with winner's config ──
    # Neural early stopping uses X_cv_val (training-dim fold) — not X_interp.
    # X_interp is reserved as a true held-out test set.
    theory_train = np.array([meta_all[train_idx[i]]["theory_classical_log2"]
                              for i in range(len(X_train))])
    primal_mask_train = np.array([meta_all[train_idx[i]]["attack"] == "primal"
                                   for i in range(len(X_train))])

    if winner_family != "poly":
        nn_predict_fns = []
        for seed_offset in range(5):   # 5-model ensemble for variance reduction
            torch.manual_seed(SEED + seed_offset)
            pred_fn, _, _, _ = fit_neural_model(
                X_train, y_train, X_cv_val, y_cv_val,
                epochs=800, lr=5e-4, hidden=(128, 64, 32),
                rank_lambda=best_lambda_cv,
                theory_tr=theory_train, primal_mask_tr=primal_mask_train
            )
            nn_predict_fns.append(pred_fn)

        def predict_nn(X):
            return np.mean([f(X) for f in nn_predict_fns], axis=0)

        y_ip_nn = predict_nn(X_interp)
        y_ep_nn = predict_nn(X_extrap) if len(X_extrap) > 0 else np.array([])
    else:
        y_ip_nn = y_ep_nn = np.array([])
        predict_nn = lambda X: np.zeros(len(X))

    # Build final predictions for winner family
    if winner_family == "poly":
        y_interp_pred = y_ip_poly
        y_extrap_pred = y_ep_poly
        best_predict = lambda X: predict_linear(poly_features(X), best_poly_w)
        best_label = "poly"
    elif winner_family == "neural":
        y_interp_pred = y_ip_nn
        y_extrap_pred = y_ep_nn
        best_predict = predict_nn
        best_label = f"neural(λ={best_lambda_cv})"
    else:  # blend
        y_interp_pred = best_beta_cv * y_ip_poly + (1 - best_beta_cv) * y_ip_nn
        y_extrap_pred = best_beta_cv * y_ep_poly + (1 - best_beta_cv) * y_ep_nn \
                        if len(y_ep_nn) > 0 else np.array([])
        best_predict = lambda X, _bw=best_poly_w, _bc=best_beta_cv, _nn=predict_nn: \
            _bc * predict_linear(poly_features(X), _bw) + (1 - _bc) * _nn(X)
        best_label = f"blend(λ={best_lambda_cv},β={best_beta_cv})"

    # ── Single held-out evaluation: PRED_SCORE on X_interp + X_extrap ──
    y_ep_p = y_extrap_pred[extrap_primal_local_idx] if len(y_extrap_pred) > 0 else np.array([])
    best_score, r2i, r2e, tc = compute_pred_score(
        y_interp, y_interp_pred, y_extrap, y_extrap_pred,
        theory_preds_extrap_primal, y_ep_p)
    print(f"\n  Best model: {best_label} (SCORE={best_score:.4f})")

    # ── NIST extrapolation ──
    extrapolate_to_nist(best_predict, nist_params, rows)

    # ── Discrepancy analysis ──
    print("\n" + "=" * 70)
    print("EMPIRICAL vs THEORETICAL DISCREPANCY")
    print("=" * 70)
    if len(X_extrap) > 0:
        for i, idx in enumerate(extrap_idx):
            m = meta_all[idx]
            print(f"  n={m['n']}  β={m['beta']:3d} ({m['attack']:6s}):  "
                  f"actual={y_extrap[i]:+7.2f}  model={y_extrap_pred[i]:+7.2f}  "
                  f"CoreSVP={m['theory_classical_log2']:+7.2f}  "
                  f"model_err={y_extrap_pred[i]-y_extrap[i]:+.2f}  "
                  f"theory_gap={y_extrap[i]-m['theory_classical_log2']:+.2f}")
            if i > 25:
                print(f"  ... ({len(extrap_idx) - i - 1} more rows)")
                break

    # ── Record & save ──
    meta_interp = [meta_all[i] for i in interp_test_idx]
    meta_extrap_list = [meta_all[i] for i in extrap_idx]
    history = record_iteration(best_score, r2i, r2e, tc, label="iter24")
    save_progress(y_interp, y_interp_pred, y_extrap, y_extrap_pred,
                  best_score, history,
                  meta_interp=meta_interp, meta_extrap=meta_extrap_list)

    elapsed = time.time() - t0
    print(f"\nCompleted in {elapsed:.1f}s")
    print(f"RESULT: PRED_SCORE={best_score:.4f}")


if __name__ == "__main__":
    main()
